---
- name: Run apt upgrade
  ansible.builtin.apt:
    upgrade: "yes"
    update_cache: true
    cache_valid_time: 432000

- name: Add riot.im repo key
  ansible.builtin.apt_key:
    url: https://packages.riot.im/debian/riot-im-archive-keyring.gpg

- name: Add riot.im repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://packages.riot.im/debian/ default main
    filename: riot-im

- name: Install riot.im
  ansible.builtin.apt:
    name: element-desktop
