---

- name: Install Go Lang
  become: false
  ansible.builtin.unarchive:
    src: "{{ golang_tar }}"
    creates: "~/go"
    remote_src: true
    dest: ~/

- name: Install Tour
  become: false
  ansible.builtin.shell:
    creates: ~/go/bin/tour
    chdir: "~/"
    cmd: PATH="~/go/bin:$PATH" ~/go/bin/go install golang.org/x/tour@latest
