---
# This playbook configure typical workstation for home
# vim: ts=2 sts=2 sw=2 et

- name: Configure as workstation
  hosts: all
  become: true
  gather_facts: true
  vars:
    timezone: Europe/Kiev
    username: "{{ lookup('env', 'USER') }}"

  roles:
    - lenovo
    - firewall
    - deps
    - unbound
    - backup
    - waydroid
    - hardware
    - sway
    - android
    - bluetooth
    - booksdigit
    - golang
    - mail
    - virt
    - windowmaker
    - foliate
    # - slavonic
    - soft
    - wps_office
    - ticktick
    - musicbrainz
    - obs_studio
    - develop
    - textract
    # - r-studio
    - brave
    - chrome
    - opera
    - vivaldi
    - viber
    - zoom
    - skype
    - fonts
    # - element
    - discord
    - calibre
    # - anydesk
    - games
    - foreign-lang
    # - teamviewer
    - whdd
    - users
