---
# This playbook configure typical workstation for home

- name: Configure as workstation
  hosts: all
  become: yes
  vars:
    - timezone: Europe/Kiev

  roles:
    - deps
    - unbound
    - virt
    - windowmaker
    - fonts
    - linssid
    - soft
    - develop
    - textract
#    - r-studio
    - chrome
    - opera
    - vivaldi
    - viber
    - skype
#    - riot.im
    - telegram
#    - calibre
    - linuxdcpp
    - anydesk
    - games
    - foreign-lang
    - teamviewer
