---
# This playbook configure typical workstation for home

- name: Configure as workstation
  hosts: all
  become: yes
  gather_facts: false
  vars:
    - timezone: Europe/Kiev

  roles:
    - deps
    - unbound
    - fonts
#    - slavonic
    - soft
    - textract
#    - r-studio
    - palemoon
    - calibre
    - foreign-lang
