---
# This playbook configure typical workstation for home

- name: Configure as workstation
  hosts: all
  vars:
    - timezone: Europe/Kiev
    - anydesk_deb: 'https://download.anydesk.com/linux/anydesk_2.9.0-1_amd64.deb'
    - teamviewer_deb: 'https://download.teamviewer.com/download/teamviewer_i386.deb'
    - rstudio_deb: 'https://download1.rstudio.org/rstudio-1.0.143-amd64.deb'
    - steam_deb: 'https://steamcdn-a.akamaihd.net/client/installer/steam.deb'
    - viber_deb: 'http://download.cdn.viber.com/cdn/desktop/Linux/viber.deb'

  roles:
    - opera
    - deps
    - windowmaker
    - linssid
    - soft
    - textract
    - r-studio
    - chrome
    - skype
    - viber
    - telegram
    - calibre
    - linuxdcpp
    - teamviewer
    - anydesk
    - steam
    - fonts
    - qemu
