---
# This playbook configure typical workstation for home
# vim: ts=2 sts=2 sw=2 et

- name: Configure as workstation
  hosts: all
  become: yes
  gather_facts: true
  vars:
    - timezone: Europe/Kiev
    - username: "{{ ansible_user_id }}"

  roles:
    - deps
    - unbound
#   - backuping
    - waydroid
    - hardware
#   - joplin
    - sway
    - android
    - bluetooth
    - booksdigit
    - golang
    - mail
    - virt
    - windowmaker
    - fonts
    - foliate
#   - slavonic
    - soft
    - keepass
    - ticktick
    - recovery
    - develop
    - textract
#   - r-studio
    - brave
    - chrome
    - opera
    - vivaldi
#   - viber
#   - zoom
    - skype
    - telegram
#   - riot.im
    - discord
    - calibre
    - anydesk
    - games
    - foreign-lang
#   - teamviewer
