---
# This playbook configure typical workstation for home

- name: Configure as workstation
  hosts: all
  become: yes
  gather_facts: true
  vars:
    - timezone: Europe/Kiev
    - username: "{{ ansible_user_id }}"

  roles:
    - deps
    - unbound
    - backuping
    - hardware
#    - joplin
    - android
    - booksdigit
    - golang
    - mail
    - virt
    - windowmaker
    - fonts
    - foliate
#    - slavonic
    - soft
    - recovery
    - develop
    - textract
#    - r-studio
    - chrome
    - opera
    - vivaldi
#    - viber
#    - zoom
    - skype
#    - riot.im
    - telegram
    - calibre
    - anydesk
    - games
    - foreign-lang
#    - teamviewer
