---

- name: Install deps
  apt:
    name:
      - libpulse-dev
      - python-dev
      - libxml2-dev
      - libxslt1-dev
      - antiword
      - unrtf
      - poppler-utils
      - pstotext
      - tesseract-ocr
      - flac
      - ffmpeg
      - lame
      - libmad0
      - libsox-fmt-mp3
      - sox
      - libjpeg-dev
      - swig

- name: Install textract
  pip:
    name: textract
    extra_args: "--user --compile"
  become: false
