---

- name: Install deps
  ansible.builtin.apt:
    name:
      - libpulse-dev
      - python3-dev
      - libxml2-dev
      - libxslt1-dev
      - antiword
      - unrtf
      - poppler-utils
      - pstotext
      - tesseract-ocr
      - flac
      - ffmpeg
      - lame
      - libmad0
      - libsox-fmt-mp3
      - sox
      - libjpeg-dev
      - swig
      - liblingua-stem-snowball-perl

- name: Install textract
  become: false
  ansible.builtin.pip:
    name: textract
    extra_args: "--user --compile --upgrade"
