---

# Change resolver to local Unbound

- name: Install Dependencies
  ansible.builtin.apt:
    name:
      - resolvconf
      - unbound
    update_cache: true

- name: Add server record to hosts
  ansible.builtin.lineinfile:
    name: /etc/hosts
    line: "192.0.47.9\twww.internic.net"

- name: Install service to update root.hints
  ansible.builtin.copy:
    dest: /etc/systemd/system/roothints.service
    owner: root
    group: root
    mode: '0644'
    src: "roothints.service"

- name: Install timer to update root.hints
  ansible.builtin.copy:
    dest: /etc/systemd/system/roothints.timer
    owner: root
    group: root
    mode: '0644'
    src: "roothints.timer"

- name: Enable timer to update root.hints
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: roothints.timer

- name: Download root.hints
  ansible.builtin.systemd:
    state: started
    enabled: false
    name: roothints.service

- name: Conifgure unbound
  ansible.builtin.copy:
    dest: /etc/unbound/unbound.conf.d/main.conf
    owner: root
    group: root
    mode: '0644'
    src: "main.conf"

- name: Enable and run unbound
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: unbound

- name: Add local resourses - cinema
  ansible.builtin.lineinfile:
    name: /etc/hosts
    line: "192.168.1.2\tcinema.galato.pp.ua\tcinema"

- name: Add local resourses - mature
  ansible.builtin.lineinfile:
    name: /etc/hosts
    line: "192.168.1.2\tmature.galato.pp.ua\tmature"

- name: Add local resourses - encycl
  ansible.builtin.lineinfile:
    name: /etc/hosts
    line: "192.168.1.2\tencycl.galato.pp.ua\tencycl"

- name: Add local resourses - munin
  ansible.builtin.lineinfile:
    name: /etc/hosts
    line: "192.168.1.2\tmunin.galato.pp.ua\tmunin"

- name: Add local resourses - mail
  ansible.builtin.lineinfile:
    name: /etc/hosts
    line: "192.168.1.2\tmail.galato.pp.ua\tmail"
