---
# Install Church Slavonic keyboard.
# More details: https://sci.ponomar.net/ru/keyboard.html
#

- name: Add Ponomar's repo
  ansible.builtin.apt_repository:
    repo: ppa:aleksandr-andreev/sci
    codename: bionic

- name: Install Churhc Slavonic keyboard
  ansible.builtin.apt:
    name:
      - m17n-cu
    update_cache: true
