---
# Steam install

- name: Accept question
  ansible.builtin.debconf:
    name: steam
    question: 'steam/question'
    value: 'I AGREE'
    vtype: 'select'

- name: Accept license
  ansible.builtin.debconf:
    name: steam
    question: 'steam/license'
    value: ''
    vtype: 'note'

- name: Add Steam
  ansible.builtin.apt:
    deb: "{{ games_steam_deb }}"

- name: Add Lutris repo
  block:
    - name: Repo key
      ansible.builtin.get_url:
        url: >-
          https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x37B90EDD4E3EFAE4
        dest: /etc/apt/keyrings/lutris.asc
        mode: '0644'
        force: true

    - name: Repo file
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch=amd64 signed-by=/etc/apt/keyrings/lutris.asc]
          http://ppa.launchpad.net/lutris-team/lutris/ubuntu jammy main
        state: present
        filename: lutris

- name: Install Lutris
  ansible.builtin.apt:
    name: lutris

- name: Install PlayOnLinux
  ansible.builtin.apt:
    name: playonlinux

- name: Install games from official repo
  ansible.builtin.apt:
    name:
      - angband
      - zangband
