---
# Steam install

- name: Accept question
  ansible.builtin.debconf:
    name: steam
    question: 'steam/question'
    value: 'I AGREE'
    vtype: 'select'

- name: Accept license
  ansible.builtin.debconf:
    name: steam
    question: 'steam/license'
    value: ''
    vtype: 'note'

- name: Add Steam
  ansible.builtin.apt:
    deb: "{{ games_steam_deb }}"

- name: Add Lutris repo
  ansible.builtin.apt_repository:
    repo: ppa:lutris-team/lutris

- name: Install Lutris
  ansible.builtin.apt:
    name: lutris

- name: Install PlayOnLinux
  ansible.builtin.apt:
    name: playonlinux

- name: Install games from official repo
  ansible.builtin.apt:
    name:
      - angband
      - zangband
