---
# Steam install

- name: Accept question
  debconf:
    name: steam
    question: 'steam/question'
    value: 'I AGREE'
    vtype: 'select'

- name: Accept license
  debconf:
    name: steam
    question: 'steam/license'
    value: ''
    vtype: 'note'

- name: Add Steam
  apt:
    deb: "{{ steam_deb }}"

- name: Add Lutris repo
  apt_repository:
    repo: ppa:lutris-team/lutris

- name: Install Lutris
  apt:
    name: lutris

- name: Install PlayOnLinux
  apt:
    name: playonlinux
