---
# Steam install
- name: Install dependencies
  apt:
    name:
      - libgl1-mesa-dri:i386
      - libgl1-mesa-glx:i386
      - libc6:i386
      - mesa-vulkan-drivers
      - mesa-vulkan-drivers:i386

- name: Accept question
  debconf:
    name: steam
    question: 'steam/question'
    value: 'I AGREE'
    vtype: 'select'

- name: Accept license
  debconf:
    name: steam
    question: 'steam/license'
    value: ''
    vtype: 'note'

- name: Add Steam
  apt:
    deb: "{{ steam_deb }}"

- name: Add Lutris repo
  apt_repository:
    repo: ppa:lutris-team/lutris

- name: Install Lutris
  apt:
    name: lutris

- name: Install PlayOnLinux
  apt:
    name: playonlinux
