---
# AnyDesk install

- name: Add repo key
  apt_key:
    url: https://keys.anydesk.com/repos/DEB-GPG-KEY
    state: present


- name: Add repo
  apt_repository:
    repo: deb http://deb.anydesk.com/ all main
    state: present
    filename: anydesk

- name: Add Anydesk
  apt:
    name: anydesk
