---

- name: Check if WPS Office is installed
  ansible.builtin.package_facts:
    manager: "auto"

- name: WPS Office Install
  ansible.builtin.apt:
    deb: "{{ wps_office_deb }}"
  when: "'wps-office' is not in ansible_facts.packages"

- name: Remove templates
  ansible.builtin.file:
    path: /etc/skel/模板
    state: absent
