---

- name: Check if WPS Office is installed
  package_facts:
    manager: "auto"

- name: WPS Office Install
  apt:
    deb: https://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/linux/11691/wps-office_11.1.0.11691.XA_amd64.deb
  when: "'wps-office' is not in ansible_facts.packages"
