---
# Steam install
- name: Install dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - libgl1-mesa-dri:i386
    - libgl1-mesa-glx:i386
    - libc6:i386

- name: Copy the package
  command: curl -L -o /tmp/steam.deb "{{ steam_deb }}"
  args:
    warn: False

- name: Accept question
  debconf:
    name: steam
    question: 'steam/question'
    value: 'I AGREE'
    vtype: 'select'

- name: Accept license
  debconf:
    name: steam
    question: 'steam/license'
    value: ''
    vtype: 'note'

- name: Add Steam
  apt:
    deb: /tmp/steam.deb
