---
# OBS Studio Install

- name: Add repo
  ansible.builtin.apt_repository:
    repo: 'ppa:obsproject/obs-studio'
    state: present

- name: Install OBS Studio
  ansible.builtin.apt:
    name: obs-studio
