---
# Waydroid install

- name: Add repo key
  ansible.builtin.apt_key:
    url: https://repo.waydro.id/waydroid.gpg
    state: present


- name: Add repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://repo.waydro.id/ jammy main
    state: present
    filename: waydroid

- name: Add Waydroid
  ansible.builtin.apt:
    name: waydroid
