---

- name: Check if Viber is installed
  ansible.builtin.package_facts:
    manager: "auto"

- name: Install Viber
  ansible.builtin.apt:
    deb: "{{ viber_deb }}"
  when: "'viber' is not in ansible_facts.packages"
