---

# Install virtualization soft

- name: Install bridge-helper permission setupper
  copy:
    dest: "/etc/apt/apt.conf.d/80qemu"
    src: "80qemu"
    group: root
    owner: root
    mode: 0644

- name: Install dependencies
  apt:
    name:
      - qemu-kvm
      - libvirt0
      - libnm-glib-dev
    update_cache: yes

- name: Install iface-up script
  copy:
    dest: "/etc/qemu-ifup"
    src: "qemu-ifup"
    group: root
    owner: root
    mode: 04755

- name: Create bridge
  nmcli:
    conn_name: 'br0'
    ifname: 'br0'
    dhcp_client_id: 'workstation'
    type: 'bridge'
    state: 'present'

- name: Add network card to bridge
  nmcli:
    conn_name: "{{ wired_card }}"
    master: 'br0'
    ifname: "{{ wired_card }}"
    type: 'bridge-slave'
    state: 'present'

- name: HDD
  lineinfile:
    create: yes
    name: /etc/udev/rules.d/39-usbmuxd.rules
    line: 'SUBSYSTEM=="usb", ATTR{idVendor}=="152d", ATTR{idProduct}=="2336", GROUP="disk"'
    group: root
    owner: root
    mode: 0644

- name: Old DevID
  lineinfile:
    create: yes
    name: /etc/udev/rules.d/39-usbmuxd.rules
    line: 'SUBSYSTEM=="usb", ATTR{idVendor}=="05ac", ATTR{idProduct}=="1281", GROUP="disk"'
    group: root
    owner: root
    mode: 0644

- name: New DevID
  lineinfile:
    create: yes
    name: /etc/udev/rules.d/39-usbmuxd.rules
    line: 'SUBSYSTEM=="usb", ATTR{idVendor}=="05ac", ATTR{idProduct}=="12a2", GROUP="disk"'
    group: root
    owner: root
    mode: 0644

- name: Get user name
  local_action: command whoami
  register: username
  become: false

- name: Add USERNAME to group kvm
  user:
    name: "{{ username.stdout }}"
    groups: kvm
    append: yes

- name: Add USERNAME to group disk
  user:
    name: "{{ username.stdout }}"
    groups: disk
    append: yes

- name: Add libvirt-qemu to group disk
  user:
    name: libvirt-qemu
    groups: disk
    append: yes
