---
# Opera install

- name: Add repo key
  ansible.builtin.get_url:
    url: https://deb.opera.com/archive.key
    dest: /etc/apt/keyrings/opera.asc
    mode: '0644'
    force: true


- name: Add repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/opera.asc] \
           https://deb.opera.com/opera-stable/ stable non-free"
    state: present
    filename: opera-stable

- name: Add Opera
  ansible.builtin.apt:
    name: opera-stable
