---
# Opera install

- name: Add repo key
  get_url:
    url: https://deb.opera.com/archive.key
    dest: /etc/apt/keyrings/opera.asc
    mode: '0644'
    force: true


- name: Add repo
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/opera.asc] https://deb.opera.com/opera-stable/ stable non-free
    state: present
    filename: opera-stable

- name: Add Opera
  apt:
    name: opera-stable
