---

- name: Check if Zoom is installed
  ansible.builtin.package_facts:
    manager: "auto"

- name: Install Zoom
  ansible.builtin.apt:
    deb: "{{ zoom_deb }}"
  when: "'zoom' is not in ansible_facts.packages"
