---

- name: Add repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E084DAB9
    state: present

- name: Add repo
  apt_repository:
    repo: deb http://cran.rstudio.com/bin/linux/ubuntu {{ ansible_distribution_release }}/
    state: present

- name: Install R-Base
  apt:
    name: r-base

- name: Install R-Base Dev
  apt:
    name: r-base-dev

- name: Copy the package
  command: curl -L -o /tmp/rstudio.deb "{{ rstudio_deb }}"

- name: Install R-Studio
  apt:
    deb: /tmp/rstudio.deb
