---

- name: Add repo key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: E084DAB9
    state: present

- name: Add repo
  ansible.builtin.apt_repository:
    repo: "deb http://cran.rstudio.com/bin/linux/ubuntu \
           {{ ansible_distribution_release }}/"
    state: present

- name: Install R-Base
  ansible.builtin.apt:
    name: r-base

- name: Install R-Base Dev
  ansible.builtin.apt:
    name: r-base-dev

- name: Check if R-Studio is installed
  ansible.builtin.package_facts:
    manager: "auto"

- name: Install R-Studio
  ansible.builtin.apt:
    deb: "{{ rstudio_deb }}"
  when: "'rstudio' is not in ansible_facts.packages"
