---

- name: Install dependencies
  apt:
    name:
      - ntpdate
      - curl
      - traceroute
      - nfs-common
      - cifs-utils
      - smbclient
      - mailutils
      - git
      - alsa-base
      - pulseaudio
      - rfkill
      - python3-pygame
      - doas
      - openssh-server
      - keychain
      - sanoid
      - restic
      - apt-file
      - hfsplus
      - whois
      - wev
      - netdiag
      - knockd
    update_cache: yes

- name: Repo for correct wpasupplicant
  apt_repository:
    repo: deb http://old-releases.ubuntu.com/ubuntu/ impish main restricted universe multiverse
    state: present
    filename: oldversion

- name: Install correct wpasupplicant
  apt:
    allow_downgrade: yes
    name:
      - wpasupplicant=2:2.9.0-21build1

- name: Freeze correct wpasupplicant
  dpkg_selections:
    name: wpasupplicant
    selection: hold


- name: Create Sanoid directory
  file:
    path: "/etc/sanoid"
    state: directory
    mode: 0755
    group: root
    owner: root

- name: Install Sanoid configuration
  copy:
    dest: "/etc/sanoid/sanoid.conf"
    src: "sanoid.conf"
    group: root
    owner: root
    mode: 0644

- name: Install Doas configuration
  copy:
    dest: "/etc/doas.conf"
    src: "doas.conf"
    group: root
    owner: root
    mode: 0644

- name: Install Storage mount - copy file
  copy:
    dest: "/etc/systemd/system/home-alet-Storage.mount"
    src: "home-alet-Storage.mount"
    group: root
    owner: root
    mode: 0644

- name: Install Storage mount - enable mount
  systemd:
    name: home-alet-Storage.mount
    state: stopped
    enabled: false
