---

- name: Install dependencies
  apt:
    name:
      - ntpdate
      - curl
      - traceroute
      - nfs-common
      - cifs-utils
      - smbclient
      - mailutils
      - git
      - alsa-base
      - pulseaudio
      - rfkill
      - python3-pygame
      - doas
      - openssh-server
      - keychain
      - sanoid
      - restic
      - apt-file
      - hfsplus
      - whois
      - wev
      - netdiag
      - knockd
    update_cache: yes

- name: Repo for correct wpasupplicant
  apt_repository:
    repo: deb http://old-releases.ubuntu.com/ubuntu/ impish main restricted universe multiverse
    state: present
    filename: oldversion

- name: Install correct wpasupplicant
  apt:
    allow_downgrade: yes
    name:
      - wpasupplicant=2:2.9.0-21build1

- name: Freeze correct wpasupplicant
  dpkg_selections:
    name: wpasupplicant
    selection: hold


- name: Create Sanoid directory
  file:
    path: "/etc/sanoid"
    state: directory
    mode: 0755
    group: root
    owner: root

- name: Install Sanoid configuration
  copy:
    dest: "/etc/sanoid/sanoid.conf"
    src: "sanoid.conf"
    group: root
    owner: root
    mode: 0644

- name: Install Doas configuration
  copy:
    dest: "/etc/doas.conf"
    src: "doas.conf"
    group: root
    owner: root
    mode: 0644

- name: Install Storage mount - copy file
  copy:
    dest: "/etc/systemd/system/home-alet-Storage.mount"
    src: "home-alet-Storage.mount"
    group: root
    owner: root
    mode: 0644

- name: Install Storage mount - enable mount
  systemd:
    name: home-alet-Storage.mount
    state: stopped
    enabled: false

- name: Install WiFi profiles - 1
  copy:
    dest: "/etc/NetworkManager/system-connections/Alet.nmconnection"
    src: "Alet.nmconnection"
    group: root
    owner: root
    mode: 0600

- name: Install WiFi profiles - 2
  copy:
    dest: "/etc/NetworkManager/system-connections/Alet'sHome.nmconnection"
    src: "Alet'sHome.nmconnection"
    group: root
    owner: root
    mode: 0600

- name: Install WiFi profiles - 3
  copy:
    dest: "/etc/NetworkManager/system-connections/Alet's Home.nmconnection"
    src: "Alet's Home.nmconnection"
    group: root
    owner: root
    mode: 0600

- name: Create log file - 1
  file:
    path: "/var/log/backup.home.aws.log"
    state: touch
    mode: 0644
    owner: alet
    group: root

- name: Create log file - 2
  file:
    path: "/var/log/backup.home.khai.log"
    state: touch
    mode: 0644
    owner: alet
    group: root

- name: Create crontab
  copy:
    src: alet.crontab
    dest: "{{ lookup('env', 'HOME') }}/crontab"
  register: crontab_result
  become: false

- name: Install crontab
  shell: crontab crontab
  args:
    chdir: "{{ lookup('env', 'HOME') }}"
  when: crontab_result.changed
  become: false

- name: Install NFS server
  apt:
    name: nfs-kernel-server

- name: Create folder for server's backups
  file:
    path: "/var/backups/server"
    state: directory
    mode: 0700
    group: backup
    owner: backup

- name: Add share for server backups
  lineinfile:
    path: /etc/exports
    line: "/var/backups/server\t192.168.1.2(rw,no_subtree_check,anonuid=34)"
