---

- name: Install dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - ntpdate
    - curl
    - bridge-utils
    - nfs-common
    - git
    - alsa-base
    - pulseaudio
    - wpasupplicant
    - rfkill
    - python-pygame
