---

- name: Install dependencies
  apt:
    name:
      - ntpdate
      - curl
      - bridge-utils
      - nfs-common
      - cifs-utils
      - smbclient
      - git
      - alsa-base
      - pulseaudio
      - wpasupplicant
      - rfkill
      - python-pygame
      - openssh-server
    update_cache: yes
