---

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - ntpdate
      - curl
      - traceroute
      - nfs-common
      - cifs-utils
      - smbclient
      - mailutils
      - git
      - alsa-base
      - pulseaudio
      - rfkill
      - python3-pygame
      - doas
      - openssh-server
      - keychain
      - sanoid
      - restic
      - apt-file
      - hfsplus
      - whois
      - wev
      - netdiag
      - knockd
    update_cache: true

- name: Repo for correct wpasupplicant
  ansible.builtin.apt_repository:
    repo: "deb http://old-releases.ubuntu.com/ubuntu/ impish \
           main restricted universe multiverse"
    state: present
    filename: oldversion

- name: Install correct wpasupplicant
  ansible.builtin.apt:
    allow_downgrade: true
    name:
      - wpasupplicant=2:2.9.0-21build1

- name: Freeze correct wpasupplicant
  ansible.builtin.dpkg_selections:
    name: wpasupplicant
    selection: hold


- name: Create Sanoid directory
  ansible.builtin.file:
    path: "/etc/sanoid"
    state: directory
    mode: '0755'
    group: root
    owner: root

- name: Install Sanoid configuration
  ansible.builtin.copy:
    dest: "/etc/sanoid/sanoid.conf"
    src: "sanoid.conf"
    group: root
    owner: root
    mode: '0644'

- name: Install Doas configuration
  ansible.builtin.copy:
    dest: "/etc/doas.conf"
    src: "doas.conf"
    group: root
    owner: root
    mode: '0644'

- name: Install Storage mount - copy file
  ansible.builtin.copy:
    dest: "/etc/systemd/system/home-alet-Storage.mount"
    src: "home-alet-Storage.mount"
    group: root
    owner: root
    mode: '0644'

- name: Install Storage mount - enable mount
  ansible.builtin.systemd:
    name: home-alet-Storage.mount
    state: stopped
    enabled: false

- name: Install WiFi profiles - 1
  ansible.builtin.copy:
    dest: "/etc/NetworkManager/system-connections/Alet.nmconnection"
    src: "Alet.nmconnection"
    group: root
    owner: root
    mode: '0600'

- name: Install WiFi profiles - 2
  ansible.builtin.copy:
    dest: "/etc/NetworkManager/system-connections/Alet'sHome.nmconnection"
    src: "Alet'sHome.nmconnection"
    group: root
    owner: root
    mode: '0600'

- name: Install WiFi profiles - 3
  ansible.builtin.copy:
    dest: "/etc/NetworkManager/system-connections/Alet's Home.nmconnection"
    src: "Alet's Home.nmconnection"
    group: root
    owner: root
    mode: '0600'

- name: Create log file - 1
  ansible.builtin.file:
    path: "/var/log/backup.home.aws.log"
    state: touch
    mode: '0644'
    owner: alet
    group: root

- name: Create log file - 2
  ansible.builtin.file:
    path: "/var/log/backup.home.khai.log"
    state: touch
    mode: '0644'
    owner: alet
    group: root

- name: Copy .deb of static-browsers-repo
  ansible.builtin.copy:
    src: static-browsers-repo_1.0-1_all.deb
    dest: /tmp/
    mode: '0644'

- name: Install static-browsers-repo
  ansible.builtin.apt:
    deb: /tmp/static-browsers-repo_1.0-1_all.deb
