---

- name: Install dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - aptitude
    - curl
    - bridge-utils
    - nfs-common
    - wmaker
    - git
    - wdm
    - alsa-base
    - wmmoonclock
    - wmcalclock
    - wmbattery
    - xterm
