---

# Install soft for developoing

- name: Add utils
  ansible.builtin.apt:
    name: git-extras

- name: Add libgdiplus, needs for KP
  ansible.builtin.apt:
    name: libgdiplus

- name: Install Key for MS repo
  ansible.builtin.apt:
    deb: >
      https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb

- name: Add https transport
  ansible.builtin.apt:
    name: apt-transport-https

- name: Update
  ansible.builtin.apt:
    update_cache: true

- name: Add .NET Core SDK
  ansible.builtin.apt:
    name:
      - dotnet-sdk-6.0
      - dotnet-sdk-8.0

- name: Perl tools for developing
  ansible.builtin.apt:
    name:
      - cpanminus
      - perl-doc

- name: Install Java
  ansible.builtin.apt:
    name:
      - openjdk-11-doc
      - openjdk-11-jdk
      - openjdk-11-jre

- name: Install Kuber repo key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    dest: /etc/apt/keyrings/kubectl.asc
    mode: '0644'
    force: true

- name: Add Kubectl repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubectl.asc] \
           https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    state: present
    filename: kubernetes

- name: Add Kubectl, AWS cli
  ansible.builtin.apt:
    name:
      - kubectl
      - awscli
      - jq
      - python3-boto3

- name: Install awscli session manager plugin
  ansible.builtin.apt:
    deb: "{{ develop_aws_ssm_plugin }}"

- name: "Add nodejs apt key"
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    dest: /etc/apt/keyrings/nodejs.asc
    mode: '0644'
    force: true

- name: "Add nodejs 18.x ppa for apt repo"
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodejs.asc] \
           https://deb.nodesource.com/node_18.x jammy main"
    state: present
    filename: nodejs
    update_cache: true

- name: Install Node.js
  ansible.builtin.apt:
    name: nodejs

- name: Install linters' depends
  ansible.builtin.apt:
    name:
      - shellcheck

- name: Install Haskell's depends
  ansible.builtin.apt:
    name:
      - libicu-dev
      - libncurses-dev
      - libgmp-dev
      - zlib1g-dev
