---

# Install soft for developoing

- name: Install Key for MS repo
  apt:
    deb: https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb

- name: Add repo universe
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - 'deb http://archive.ubuntu.com/ubuntu/ bionic universe'
    - 'deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe'
    - 'deb http://security.ubuntu.com/ubuntu/ bionic-security universe'

- name: Add https transport
  apt:
    name: apt-transport-https

- name: Update
  apt:
    update_cache: yes

- name: Add .NET Core SDK
  apt:
    name: dotnet-sdk-3.1
