---

# Install soft for developoing

- name: Add utils
  apt:
    name: git-extras

- name: Add libgdiplus, needs for KP
  apt:
    name: libgdiplus

- name: Install Key for MS repo
  apt:
    deb: https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb

- name: Add https transport
  apt:
    name: apt-transport-https

- name: Update
  apt:
    update_cache: yes

- name: Add .NET Core SDK
  apt:
    name: dotnet-sdk-6.0

- name: Perl tools for developing
  apt:
    name:
      - cpanminus
      - perl-doc

- name: Install Java
  apt:
    name:
      - openjdk-11-doc
      - openjdk-11-jdk
      - openjdk-11-jre

- name: Install Kuber repo key
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/keyrings/kubectl.asc
    mode: '0644'
    force: true

- name: Add Kubectl repo
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubectl.asc] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: Add Kubectl, AWS cli
  apt:
    name:
      - kubectl
      - awscli
      - jq
      - python3-boto3

- name: Install awscli session manager plugin
  apt:
    deb: "{{ aws_ssm_plugin }}"

- name: "Add nodejs apt key"
  get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    dest: /etc/apt/keyrings/nodejs.asc
    mode: '0644'
    force: true

- name: "Add nodejs 18.x ppa for apt repo"
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/nodejs.asc] https://deb.nodesource.com/node_18.x jammy main
    state: present
    filename: nodejs
    update_cache: true

- name: Install Node.js
  apt:
    name: nodejs
