---

# Postfix configure and install

- name: Configure Postfix
  ansible.builtin.debconf:
    name: postfix
    question: 'postfix/main_mailer_type'
    vtype: 'select'
    value: 'Satellite system'

- name: Configure Postfix
  ansible.builtin.debconf:
    name: postfix
    question: 'postfix/mailname'
    vtype: 'string'
    value: "{{ ansible_host }}"

- name: Configure Postfix
  ansible.builtin.debconf:
    name: postfix
    question: 'postfix/relayhost'
    vtype: 'string'
    value: ""

- name: Configure Postfix
  ansible.builtin.debconf:
    name: postfix
    question: 'postfix/root_address'
    vtype: 'string'
    value: "{{ username }}"

- name: Configure Postfix
  ansible.builtin.debconf:
    name: postfix
    question: 'postfix/destinations'
    vtype: 'string'
    value: "{{ ansible_host }}, localhost.localdomain, localhost"

- name: Configure Postfix
  ansible.builtin.debconf:
    name: postfix
    question: 'postfix/mynetworks'
    vtype: 'string'
    value: "127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128"

- name: Configure Postfix
  ansible.builtin.debconf:
    name: postfix
    question: 'postfix/mailbox_limit'
    vtype: 'string'
    value: "0"

- name: Configure Postfix
  ansible.builtin.debconf:
    name: postfix
    question: 'postfix/recipient_delim'
    vtype: 'string'
    value: "+"

- name: Configure Postfix
  ansible.builtin.debconf:
    name: postfix
    question: 'postfix/protocols'
    vtype: 'string'
    value: "ipv4"

- name: Install Postfix
  ansible.builtin.apt:
    name: postfix

###############

- name: Install local mail
  ansible.builtin.apt:
    name:
      - dovecot-imapd
      - thunderbird-locale-ru

- name: Configure dovecot
  ansible.builtin.lineinfile:
    path: "/etc/dovecot/dovecot.conf"
    regexp: '^listen.*'
    insertafter: '^#listen'
    line: listen = 127.0.0.1
  notify: Restart dovecot
