---

- name: Check if Discord is installed
  ansible.builtin.package_facts:
    manager: "auto"

- name: Discord Install
  ansible.builtin.apt:
    deb: "{{ discord_deb }}"
  when: "'discord' is not in ansible_facts.packages"
