---

- name: Add kernel param
  lineinfile:
    path: "/etc/default/grub"
    regexp: ^GRUB_CMDLINE_LINUX_DEFAULT="(?!.*?(tpm_tis.interrupts=0))(.*)
    line: GRUB_CMDLINE_LINUX_DEFAULT="tpm_tis.interrupts=0 \2
    backrefs: yes
