---

- name: Add kernel param
  lineinfile:
    path: "/etc/default/grub"
    regexp: ^GRUB_CMDLINE_LINUX_DEFAULT="(?!.*?(tpm_tis.interrupts=0))(.*)
    line: GRUB_CMDLINE_LINUX_DEFAULT="tpm_tis.interrupts=0 \2
    backrefs: yes

# https://wiki.ubuntu.com/IntelQuickSyncVideo
- name: Install Video drivers & hardware utils
  apt:
    name:
      - ubuntu-restricted-addons
      - vainfo
      - tlp

- name: Set bounds for laptop battery
  command:
    cmd: /usr/sbin/tlp setcharge 70 80 BAT0

