---
# Vivaldi install

- name: Run apt upgrade
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 432000

- name: Add repo key
  ansible.builtin.apt_key:
    url: https://repo.vivaldi.com/archive/linux_signing_key.pub
    state: present


- name: Add repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://repo.vivaldi.com/archive/deb/ stable main
    state: present
    filename: vivaldi-stable

- name: Add Vivaldi
  ansible.builtin.apt:
    name: vivaldi-stable
