---

- name: Check if TickTick is installed
  package_facts:
    manager: "auto"

- name: TickTick Install
  apt:
    deb: https://appest-public.s3.amazonaws.com/download/linux/linux_deb_x64/ticktick-1.0.60-amd64.deb
  when: "'ticktick' is not in ansible_facts.packages"
