---

- name: Check if TickTick is installed
  ansible.builtin.package_facts:
    manager: "auto"

- name: TickTick Install
  ansible.builtin.apt:
    deb: "{{ ticktick_deb }}"
  when: "'ticktick' is not in ansible_facts.packages"
