---

# Soft list by article 'Создание_электронной_копии_книги_в_формате_DjVu_в_Linux'
# on ru.wikibooks.org
#

- name: Install soft for books digitizating
  ansible.builtin.apt:
    name:
      - geeqie
      - viewnior
      - djvulibre-bin
      - tesseract-ocr
      - tesseract-ocr-eng
      - tesseract-ocr-rus
      - tesseract-ocr-ukr
      - yagf
      - ocrfeeder
      - qpdfview
      - qpdfview-djvu-plugin
      - qpdfview-translations
      - djview4
      - python3-djvu
      - python-djvu-doc
      - gscan2pdf

- name: Utils for working with Pdf
  ansible.builtin.apt:
    name:
      - poppler-utils
      - pdftk
      - pdfposter

- name: Add ScanTailor repo
  block:
    - name: Repo key
      ansible.builtin.get_url:
        url: >-
          https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA4BCBD87CEF9E52D
        dest: /etc/apt/keyrings/scantailor.asc
        mode: '0644'
        force: true

    - name: Repo file
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch=amd64 signed-by=/etc/apt/keyrings/scantailor.asc]
          https://ppa.launchpadcontent.net/alex-p/scantailor/ubuntu
          jammy main
        state: present
        filename: scantailor

- name: Install ScanTailor
  ansible.builtin.apt:
    name:
      - scantailor-advanced

- name: Script for converting
  become: false
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ashipunov/img2djvu/master/img2djvu
    dest: ~/bin/img2djvu
    mode: '0755'
