---
# Display Manager install

- name: Add Sway
  ansible.builtin.apt:
    name:
      - sway
      - swayidle
      - swaylock
      - foot
      - wob
      - j4-dmenu-desktop
      - i3blocks
      - mako-notifier
      - dunst
      - grim
      - slurp
      - wl-clipboard
      - ydotool
      - waypipe

# https://github.com/emersion/mako/issues/257
- name: Install AppArmor permission to bus (for mako) - 1
  ansible.builtin.copy:
    dest: /etc/apparmor.d/local/fr.emersion.Mako
    owner: root
    group: root
    mode: '0644'
    src: "fr.emersion.Mako"
  notify: Restart apparmor

- name: Install AppArmor permission to bus (for mako) - 2
  ansible.builtin.lineinfile:
    name: /etc/apparmor.d/fr.emersion.Mako
    regexp: (\s*)#\s*include if exists <local/fr.emersion.Mako>\s*
    line: \1include if exists <local/fr.emersion.Mako>
    backrefs: true
  notify: Restart apparmor

- name: Brightness regulator
  ansible.builtin.apt:
    name: brightnessctl

- name: Add USERNAME to group video
  ansible.builtin.user:
    name: "{{ username }}"
    groups:
      - video
      - audio
    append: true
