---
# Install soft from standart repository

- name: Add KeePassXC repo
  apt_repository:
    repo: ppa:phoerious/keepassxc


- name: Install VLC, Audacity, Handbrake, Gimp, Blender, Dropbox, Transmission, PWgen, Keepass2, eSpeak, mount.nfs, iperf, tree, clamav, pv
  apt:
    name:
      - dc
      - bc
      - zsh-doc
      - vim
      - nvme-cli
      - vlc
      - vlc-plugin-bittorrent
      - cmus
      - unrar
      - audacious
      - mp3wrap
      - mercurial
      - handbrake
      - handbrake-cli
      - mencoder
      - mplayer-doc
      - audacity
      - soundconverter
      - easytag
      - gimp
      - gimp-help-ru
      - darktable
      - blender
      - nautilus-dropbox
      - transmission
      - wireshark
      - stellarium
      - pwgen
      - secure-delete
      - keepassxc
      - espeak
      - glmark2
      - firefox
      - w3m
      - thunderbird
      - kcharselect
      - inkscape
      - sigil
      - okular-extra-backends
      - sxiv
      - gthumb
      - zathura-pdf-poppler
      - zathura-djvu
      - pdf-presenter-console
      - qpdf
      - pdftk
      - pandoc
      - poppler-utils
      - anki
      - virt-manager
      - linssid
      - iperf
      - smartmontools
      - tlp
      - tree
      - locate
      - multitail
      - task-spooler
      - clamav
      - pv
      - xzdec
      - zstd
      - dict
      - dictd
      - dict-freedict-eng-rus
      - texlive-lang-cyrillic
      - texlive-bibtex-extra
      - texlive-publishers
      - texlive-science
      - texlive-xetex
      - texlive-luatex
      - texlive-lang-english
      - hevea
      - hevea-doc
      - libreoffice-impress
      - libreoffice-calc
      - libreoffice-writer
      - libreoffice-l10n-ru
      - wukrainian
      - hunspell-en-us
      - hunspell-ru
      - hunspell-uk
      - mythes-en-us
      - mythes-ru
      - mythes-uk
      - hyphen-en-us
      - hyphen-ru
      - hyphen-uk
      - winbind
      - xpad
      - xclip
      - freerdp2-x11
      - mutt
      - gramps
      - tj3
      - ncdu
      - parallel
      - i3
      - zeal
      - powertop
      - tmux
      - hwb
      - mtree-netbsd
      - xbacklight
      - quassel
      - ipmitool
      - pinfo
      - texinfo
      - at
      - graphicsmagick
      - why3
      - why3-coq
      - why3-examples
    update_cache: yes

- name: Install Spyder3, Python version of Matlab
  apt:
    name:
      - python3-sympy
      - pandoc-citeproc
      - fonts-linuxlibertine
      - python3-sphinx-rtd-theme
      - latexmk
      - python3-pandas
      - python3-scipy 
      - spyder3

#- name: Install LanguageTool
#  snap:
#    name:
#      - languagetool
#      - google-play-music-desktop-player

- name: Install githug
  gem:
    name: githug
    user_install: no
    state: latest

- name: Install Dolphin file manager with mediainfo support
  apt:
    name:
      - dolphin
      - breeze-icon-theme

- name: Install tutors
  apt:
    name:
      - c++-annotations-html
      - c++-annotations-pdf
      - coq-doc-html
      - coq-doc-pdf
      - cwcp
      - dvorak7min
      - fretsonfire
      - gccintro
      - gnubg
      - junior-typing
      - klavaro
      - ktouch
      - python3.8-doc
      - tipp10
      - tuxtype
      - why3-doc-html
      - why3-doc-pdf

- name: Duplicity depends
  apt:
    name:
      - gettext
      - librsync-dev
      - gpg
    update_cache: yes

- name: Install duplicity
  pip:
    name: duplicity
    extra_args: "--user --compile"
  become: false

- name: Install fork of youtube-dl
  pip:
    name: yt-dlp
    state: latest
    extra_args: "--user --compile"
  become: false

- name: Add USERNAME to group dialout for EggBot
  user:
    name: "{{ username.stdout }}"
    groups: dialout
    append: yes

- name: Prequire for next tasks
  apt:
    name: python-psutil

- name: Set Type of Powersaving on login screen
  become: yes
  become_user: gdm
  become_method: sudo
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
    value: "'blank'"

- name: Set Timout of Powersaving on login screen
  become: yes
  become_user: gdm
  become_method: sudo
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout"
    value: '30'

- name: Set Type of Powersaving on login screen
  become: yes
  become_user: gdm
  become_method: sudo
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/lid-close-ac-action"
    value: "'blank'"

