---
# Install soft from standart repository

- name: Install VLC, Audacity, Handbrake, Gimp, Blender, Dropbox, Transmission, PWgen, Keepass2, eSpeak, mount.nfs, vagrant, iperf, tree, clamav, pv
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - dc
    - bc
    - vim
    - vlc
    - cmus
    - audacious
    - mercurial
    - handbrake
    - handbrake-cli
    - audacity
    - soundconverter
    - easytag
    - gimp
    - gimp-help-ru
    - blender
    - python-sympy
    - nautilus-dropbox
    - transmission
    - stellarium
    - pwgen
    - keepass2
    - espeak
    - glmark2
    - firefox
    - thunderbird
    - inkscape
    - anki
    - vagrant
    - virt-manager
    - iperf
    - tree
    - clamav
    - pv
    - xzdec
    - dict
    - dictd
    - dict-freedict-eng-rus
    - zathura-pdf-poppler
    - texlive-lang-cyrillic
    - texlive-bibtex-extra
    - texlive-publishers
    - texlive-science
    - libreoffice-impress
    - texmaker
    - texstudio
    - playonlinux

#- name: Install LanguageTool
#  snap:
#    name:
#      - languagetool

- name: Install youtube-dl
  pip:
    name: youtube-dl
    extra_args: --user
  become: false
