---
# Install soft from standart repository

- name: Install soft which doesn't need tuning
  ansible.builtin.apt:
    name:
      - dc
      - bc
      - exuberant-ctags
      - gpg
      - remind
      - libnotify-bin
      - vorbis-tools
      - zsh-doc
      - vim
      - nvme-cli
      - vlc
      - vlc-plugin-bittorrent
      - cmus
      - mediainfo
      - mkvtoolnix
      - unrar
      - audacious
      - mp3wrap
      - mercurial
      - handbrake
      - handbrake-cli
      - mencoder
      - mplayer-doc
      - mpv
      - audacity
      - soundconverter
      - easytag
      - gimp
      - gimp-help-ru
      - simple-scan
      - darktable
      - blender
      - shotcut
      - nautilus-dropbox
      - vifm
      - transmission
      - ctorrent
      - qbittorrent
      - ncdc
      - stellarium
      - pwgen
      - etherwake
      - wakeonlan
      - secure-delete
      - espeak
      - glmark2
      - w3m
      - lynx
      - kiwix
      - kcharselect
      - inkscape
      - sigil
      - okular-extra-backends
      - yatm
      - sxiv
      - gthumb
      - zathura-pdf-poppler
      - zathura-djvu
      - pdf-presenter-console
      - qpdf
      - pdftk
      - pandoc
      - poppler-utils
      - anki
      - virt-manager
      - neofetch
      - smartmontools
      - tree
      - locate
      - multitail
      - task-spooler
      - clamav
      - pv
      - progress
      - xzdec
      - zstd
      - dict
      - dictd
      - dict-freedict-eng-rus
      - texlive-pstricks
      - texlive-lang-cyrillic
      - texlive-publishers
      - texlive-science
      - texlive-xetex
      - texlive-luatex
      - texlive-lang-english
      - texlive-bibtex-extra
      - texlive-fonts-extra
      - biber
      - hevea
      - hevea-doc
      - libreoffice-impress
      - libreoffice-calc
      - libreoffice-writer
      - libreoffice-l10n-ru
      - wukrainian
      - hunspell-en-us
      - hunspell-ru
      - hunspell-uk
      - mythes-en-us
      - mythes-ru
      - mythes-uk
      - hyphen-en-us
      - hyphen-ru
      - hyphen-uk
      - winbind
      - xpad
      - xclip
      - freerdp2-x11
      - mutt
      - gramps
      - tj3
      - vim-tjp
      - ncdu
      - parallel
      - zeal
      - powertop
      - nethogs
      - tmux
      - hwb
      - mtree-netbsd
      - xbacklight
      - quassel
      - ipmitool
      - pinfo
      - texinfo
      - at
      - graphicsmagick
      - hugo
      - zimwriterfs
      - keepassxc
    update_cache: true

- name: Make ZSH default
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /usr/bin/zsh

- name: Configure Wireshark
  ansible.builtin.debconf:
    name: wireshark-common
    question: 'wireshark-common/install-setuid'
    value: 'true'
    vtype: 'select'

# Linssid needs root rights and ordinary user environment,
# so run it as 'sudo -E linssid'
- name: Install Network Utils (Wireshark & Co.)
  ansible.builtin.apt:
    name:
      - wireshark
      - dsniff
      - nmap
      - linssid
      - iperf

- name: Add User to group wireshark
  ansible.builtin.user:
    name: "{{ username }}"
    groups: wireshark
    append: true

- name: Install systemsoft
  ansible.builtin.apt:
    name:
      - gpart
      - parted
      - testdisk
      - gddrescue         # https://habrahabr.ru/post/236977/
      - safecopy
      - ddrutility
      - ddrescueview
      - rdfind
      - reptyr
      - alien

- name: Check if FreePlane is installed
  ansible.builtin.package_facts:
    manager: "auto"

- name: Install MindMap (FreePlane)
  ansible.builtin.apt:
    deb: "{{ soft_freeplane_url }}"
  when: "'freeplane' is not in ansible_facts.packages"

- name: Install maps
  ansible.builtin.apt:
    name:
      - qgis
      - marble
      - josm
      - josm-l10n

- name: Install Spyder3, Python version of Matlab
  ansible.builtin.apt:
    name:
      - python3-sympy
      - pandoc-citeproc
      - fonts-linuxlibertine
      - python3-sphinx-rtd-theme
      - latexmk
      - python3-pandas
      - python3-scipy
      - spyder3

- name: Install githug
  community.general.gem:
    name: githug
    user_install: false

- name: Install Java support for OpenOffice
  ansible.builtin.apt:
    name:
      - libreoffice-java-common

- name: Install Dolphin file manager with mediainfo support
  ansible.builtin.apt:
    name:
      - dolphin
      - breeze-icon-theme

- name: Install tutors
  ansible.builtin.apt:
    name:
      - c++-annotations-html
      - c++-annotations-pdf
      - coq-doc-html
      - coq-doc-pdf
      - xorg-docs
      - libpam-doc
      - cwcp
      - dvorak7min
      - gccintro
      - gnubg
      - klavaro
      - ktouch
      - python3.10-doc
      - tipp10

- name: Install child soft
  ansible.builtin.apt:
    name:
      - junior-typing
      - tuxtype

- name: Install command line readers
  ansible.builtin.pip:
    name:
      - epr-reader
      - epy-reader
    extra_args: "--user --compile"
  become: false

- name: Install fork of youtube-dl
  ansible.builtin.pip:
    name: yt-dlp
    extra_args: "--user --compile"
  become: false

- name: Add User to group dialout for EggBot
  ansible.builtin.user:
    name: "{{ username }}"
    groups: dialout
    append: true

- name: Prequire for next tasks
  ansible.builtin.apt:
    name: python3-psutil

- name: Set Type of Powersaving on login screen
  become: true
  become_user: gdm
  become_method: ansible.builtin.sudo
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
    value: "'blank'"

- name: Set Timout of Powersaving on login screen
  become: true
  become_user: gdm
  become_method: ansible.builtin.sudo
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout"
    value: '30'

- name: Set Type of Powersaving on login screen
  become: true
  become_user: gdm
  become_method: ansible.builtin.sudo
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/power/lid-close-ac-action"
    value: "'blank'"

- name: Add Neovim repo
  ansible.builtin.apt_repository:
    repo: "deb https://ppa.launchpadcontent.net/neovim-ppa/stable/ubuntu \
           jammy main"
    state: present
    filename: neovim

- name: Install Neovim
  ansible.builtin.apt:
    name: neovim
