---
# Install soft from standart repository

- name: Install VLC, Audacity, Handbrake, Gimp, Blender, Dropbox, Transmission, PWgen, Keepass2, eSpeak, mount.nfs, iperf, tree, clamav, pv
  apt:
    name:
      - dc
      - bc
      - gpg
      - remind
      - libnotify-bin
      - vorbis-tools
      - zsh-doc
      - vim
      - nvme-cli
      - vlc
      - vlc-plugin-bittorrent
      - cmus
      - mediainfo
      - unrar
      - audacious
      - mp3wrap
      - mercurial
      - handbrake
      - handbrake-cli
      - mencoder
      - mplayer-doc
      - audacity
      - soundconverter
      - easytag
      - gimp
      - gimp-help-ru
      - darktable
      - blender
      - nautilus-dropbox
      - transmission
      - ctorrent
      - qbittorrent
      - ncdc
      - stellarium
      - pwgen
      - secure-delete
      - espeak
      - glmark2
      - w3m
      - lynx
      - kcharselect
      - inkscape
      - sigil
      - okular-extra-backends
      - yatm
      - sxiv
      - gthumb
      - zathura-pdf-poppler
      - zathura-djvu
      - pdf-presenter-console
      - qpdf
      - pdftk
      - pandoc
      - poppler-utils
      - anki
      - virt-manager
      - linssid
      - neofetch
      - iperf
      - smartmontools
      - tlp
      - tree
      - locate
      - multitail
      - task-spooler
      - clamav
      - pv
      - progress
      - xzdec
      - zstd
      - dict
      - dictd
      - dict-freedict-eng-rus
      - texlive-pstricks
      - texlive-lang-cyrillic
      - texlive-publishers
      - texlive-science
      - texlive-xetex
      - texlive-luatex
      - texlive-lang-english
      - texlive-bibtex-extra
      - texlive-fonts-extra
      - biber
      - hevea
      - hevea-doc
      - libreoffice-impress
      - libreoffice-calc
      - libreoffice-writer
      - libreoffice-l10n-ru
      - wukrainian
      - hunspell-en-us
      - hunspell-ru
      - hunspell-uk
      - mythes-en-us
      - mythes-ru
      - mythes-uk
      - hyphen-en-us
      - hyphen-ru
      - hyphen-uk
      - winbind
      - xpad
      - xclip
      - freerdp2-x11
      - mutt
      - gramps
      - tj3
      - vim-tjp
      - ncdu
      - parallel
      - zeal
      - powertop
      - tmux
      - hwb
      - mtree-netbsd
      - xbacklight
      - quassel
      - ipmitool
      - pinfo
      - texinfo
      - at
      - graphicsmagick
      - hugo
      - zimwriterfs
    update_cache: yes

- name: Make ZSH default
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh

- name: Configure Wireshark
  debconf:
    name: wireshark-common
    question: 'wireshark-common/install-setuid'
    value: 'true'
    vtype: 'select'

- name: Install Network Utils (Wireshark & Ko.)
  apt:
    name:
      - wireshark
      - dsniff
      - nmap

- name: Add User to group wireshark
  user:
    name: "{{ username }}"
    groups: wireshark
    append: yes

- name: Install systemsoft
  apt:
    name:
      - gpart
      - parted
      - testdisk
      - gddrescue # https://habrahabr.ru/post/236977/
      - safecopy
      - ddrutility
      - ddrescueview
      - rdfind
      - reptyr
      - alien

- name: Install MindMap
  apt:
    name:
      - vym
      - planfacile
      - minder
      - freeplane

- name: Install maps
  apt:
    name:
      - qgis
      - marble
      - josm
      - josm-l10n

- name: Install Spyder3, Python version of Matlab
  apt:
    name:
      - python3-sympy
      - pandoc-citeproc
      - fonts-linuxlibertine
      - python3-sphinx-rtd-theme
      - latexmk
      - python3-pandas
      - python3-scipy 
      - spyder3

#- name: Install LanguageTool
#  snap:
#    name:
#      - languagetool
#      - google-play-music-desktop-player

- name: Install githug
  gem:
    name: githug
    user_install: no
    state: latest

- name: Install Dolphin file manager with mediainfo support
  apt:
    name:
      - dolphin
      - breeze-icon-theme

- name: Install tutors
  apt:
    name:
      - c++-annotations-html
      - c++-annotations-pdf
      - coq-doc-html
      - coq-doc-pdf
      - xorg-docs
      - libpam-doc
      - cwcp
      - dvorak7min
      - gccintro
      - gnubg
      - klavaro
      - ktouch
      - python3.10-doc
      - tipp10

- name: Install child soft
  apt:
    name:
      - junior-typing
      - tuxtype

- name: Install fork of youtube-dl
  pip:
    name: yt-dlp
    state: latest
    extra_args: "--user --compile"
  become: false

- name: Add USERNAME to group dialout for EggBot
  user:
    name: "{{ username }}"
    groups: dialout
    append: yes

- name: Prequire for next tasks
  apt:
    name: python3-psutil

- name: Set Type of Powersaving on login screen
  become: yes
  become_user: gdm
  become_method: sudo
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
    value: "'blank'"

- name: Set Timout of Powersaving on login screen
  become: yes
  become_user: gdm
  become_method: sudo
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout"
    value: '30'

- name: Set Type of Powersaving on login screen
  become: yes
  become_user: gdm
  become_method: sudo
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/lid-close-ac-action"
    value: "'blank'"

