---
# Install soft from standart repository

- name: Add KeePassXC repo
  apt_repository:
    repo: ppa:phoerious/keepassxc


- name: Install VLC, Audacity, Handbrake, Gimp, Blender, Dropbox, Transmission, PWgen, Keepass2, eSpeak, mount.nfs, iperf, tree, clamav, pv
  apt:
    name:
      - dc
      - bc
      - vim
      - vlc
      - vlc-plugin-bittorrent
      - cmus
      - unrar
      - audacious
      - mercurial
      - handbrake
      - handbrake-cli
      - mencoder
      - mplayer-doc
      - audacity
      - soundconverter
      - easytag
      - gimp
      - gimp-help-ru
      - blender
      - nautilus-dropbox
      - transmission
      - stellarium
      - pwgen
      - keepassxc
      - espeak
      - glmark2
      - firefox
      - w3m
      - thunderbird
      - kcharselect
      - inkscape
      - sigil
      - okular-extra-backends
      - nomacs
      - zathura-pdf-poppler
      - zathura-djvu
      - pdf-presenter-console
      - anki
      - virt-manager
      - linssid
      - iperf
      - tree
      - multitail
      - task-spooler
      - clamav
      - pv
      - xzdec
      - zstd
      - dict
      - dictd
      - dict-freedict-eng-rus
      - texlive-lang-cyrillic
      - texlive-bibtex-extra
      - texlive-publishers
      - texlive-science
      - texlive-xetex
      - texlive-luatex
      - libreoffice-impress
      - libreoffice-calc
      - libreoffice-writer
      - libreoffice-l10n-ru
      - texmaker
      - texstudio
      - winbind
      - xpad
      - xclip
      - mutt
      - gramps
      - ncdu
      - parallel
      - i3
      - zeal
    update_cache: yes

- name: Install Spyder3, Python version of Matlab
  apt:
    name:
      - python3-sympy
      - pandoc-citeproc
      - fonts-linuxlibertine
      - python3-sphinx-rtd-theme
      - latexmk
      - python3-pandas
      - python3-scipy 
      - spyder3

#- name: Install LanguageTool
#  snap:
#    name:
#      - languagetool
#      - google-play-music-desktop-player

- name: Install githug
  gem:
    name: githug
    user_install: no
    state: latest

- name: Duplicity depends
  apt:
    name:
      - gettext
      - librsync-dev
      - gpg
    update_cache: yes

- name: Install duplicity
  pip:
    name: duplicity
    extra_args: "--user --compile"
  become: false

- name: Install youtube-dl
  pip:
    name: youtube-dl
    extra_args: "--user --compile"
  become: false

- name: Add USERNAME to group dialout for EggBot
  user:
    name: "{{ username.stdout }}"
    groups: dialout
    append: yes

