---
# Install tools helping with english language books

- name: Add GoldenDict
  ansible.builtin.apt:
    name: goldendict

- name: Add console StarDict
  ansible.builtin.apt:
    name: sdcv

- name: Create directory for dictionaries
  ansible.builtin.file:
    path: /usr/share/stardict/dic
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Unpack dictionary
  ansible.builtin.unarchive:
    src: "{{ fl_dictionary }}"
    remote_src: true
    dest: /usr/share/stardict/dic
    extra_opts: --strip-components=1
