---
# Install tools helping with english language books

- name: Add console StarDict
  apt:
    name: sdcv

- name: Create directory for dictionaries
  file:
    path: /usr/share/stardict/dic
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Download dictionary
  get_url:
    url: "{{ dictionary }}"
    dest: /usr/share/stardict/dic/
    owner: root
    group: root
    mode: 0644
