---
# Install tools helping with english language books

- name: Add console StarDict
  apt:
    name: sdcv

- name: Create directory for dictionaries
  file:
    path: /usr/share/stardict/dic
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Unpack dictionary
  unarchive:
    src: "{{ dictionary }}"
    remote_src: yes
    dest: /usr/share/stardict/dic
    extra_opts: --strip-components=1
