---
# MusicBrainz Install

- name: Add repo
  ansible.builtin.apt_repository:
    repo: 'ppa:musicbrainz-developers/stable'
    state: present

- name: Install MusicBrainz
  ansible.builtin.apt:
    name: picard
