---

- name: Accept license
  ansible.builtin.debconf:
    name: ttf-mscorefonts-installer
    question: 'msttcorefonts/accepted-mscorefonts-eula'
    value: 'true'
    vtype: 'select'

- name: Install Microsoft Fonts
  ansible.builtin.apt:
    name:
      - ttf-mscorefonts-installer
    update_cache: true

# Needs for layout indicator in 22.04
- name: Remove Noto Emoji
  ansible.builtin.apt:
    name:
      - fonts-noto-color-emoji
    state: 'absent'
