---

- name: Accept license
  debconf:
    name: ttf-mscorefonts-installer
    question: 'msttcorefonts/accepted-mscorefonts-eula'
    value: 'true'
    vtype: 'select'

- name: Install Microsoft Fonts
  apt:
    # 20.04 Fix
#    deb: http://ftp.de.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.8_all.deb
    name:
      - ttf-mscorefonts-installer
    update_cache: yes

# Needs for layout indicator in 22.04
- name: Remove Noto Emoji
  apt:
    name:
      - fonts-noto-color-emoji
    state: 'absent'
